steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mutual-fund-api', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mutual-fund-api']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mutual-fund-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mutual-fund-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},PGUSER=${_PGUSER},PGPASSWORD=${_PGPASSWORD},PGHOST=${_PGHOST},PGPORT=${_PGPORT},PGDATABASE=${_PGDATABASE}'

# Environment variables (set these in Cloud Build triggers)
substitutions:
  _DATABASE_URL: 'postgresql://postgres:your-password@your-host:5432/your-database'
  _PGUSER: 'postgres'
  _PGPASSWORD: 'your-password'
  _PGHOST: 'your-host'
  _PGPORT: '5432'
  _PGDATABASE: 'your-database'

images:
  - 'gcr.io/$PROJECT_ID/mutual-fund-api'