services:
  - type: web
    name: mutual-fund-api
    env: python
    buildCommand: curl -sSL https://install.python-poetry.org | python3 - && $HOME/.local/bin/poetry install --no-interaction --no-ansi
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: DATABASE_URL
        sync: false  # This means it's manually set in Render dashboard
      - key: PYTHON_VERSION
        value: 3.11.1
      - key: POETRY_VIRTUALENVS_CREATE
        value: false
    healthCheckPath: /api/funds